### ISSUE TITLE
error when signAndSubmitTransaction

### ISSUE THREAD

**Issue by mideng2** [razorlabsorg/razorkit#11]
Hello,  While using Razor Wallet, I encountered an error when the wallet was invoking a smart contract. And it looks like it's constantly loading the gas fee. This issue started occurring on December 17th. Could it be due to an error in your recent version upgrade? Could you please help troubleshoot this? Thank you very much.
![image](https://github.com/user-attachments/assets/6237b537-9a61-4675-9820-b669d4248252)

**Comment by Coradoyar** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
